name: Publish BDD Report

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --no-restore --configuration Release

    - name: Run tests and generate BDD report
      run: dotnet test --no-build --logger "trx;LogFileName=test-results.trx"

    - name: Install SpecFlow.Plus.LivingDoc CLI
      run: dotnet tool install --global SpecFlow.Plus.LivingDoc.CLI

    - name: Generate LivingDoc report
      run: |
        export PATH="$PATH:~/.dotnet/tools"
        livingdoc test-assembly ./Calculator.Domain.Tests/bin/Debug/net6.0/Calculator.Domain.Tests.dlll -t ./Calculator.Domain.Tests/bin/Debug/net6.0/TestExecution.json  -o bdd-report

    - name: Deploy report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./bdd-report
        publish_branch: gh-pages
        keep_files: true
